name: cif

channels:
- defaults
- conda-forge

dependencies:
- pip
- future
- ipython
- jupyter
- matplotlib
- numpy
- Pillow
- PyYAML
- scikit-learn
- scipy
- torch
- torchvision

# Section for things that for some reason has to be installed with pip
# For example all packages installed from git, add `- git+https://...`
# - pip:
