root_dir: TODO
root_embs_dir: TODO
save_models_dir: TODO
save_models_dir_backup: TODO
load_models_dir: TODO
resume_dataset_mean: TODO
resume_dataset_std: TODO
tensorboard_dir: TODO

use_EMD: False # False - Chamfer Distance
load_models: False # set False unless pretrained
use_random_dataloader: True

batch_size: 2
batch_size_if_random_split: 50
aggregation_steps: 1
n_epochs: 1000
n_neurons: 512
type_emb: '2r'
arch_type: 'dense_net'
n_flows_F: 10
n_flows_G: 5
l_rate: 0.0001
emb_dim: 32
x_noise: 0.0001
w_noise: 0.01
prior_z_var: 1.0
#prior_e_var: !!python/tuple [1.0]
prior_e_var: 1.0

####### PointNet encoder style args #######
# total number of points in a single batch is equal to the number of objects
# per batch, a'ka batch_size, and number of points
num_of_points_per_object: 60
load_pretrained: False
pretrained_path: TODO

####### PointFlow-related args #######

# these two does not influence the result, they're needed for comptability
# with point flow loaders
tr_sample_size: 2048
te_sample_size: 2048
#

normalize_per_shape: false
normalize_std_per_axis: false
scale: 1.0
categories: ["airplane"]