save_models_dir: '/home/mstypulkowski/CIF/saves/Saved_models_2101/'
save_models_dir_backup: '/home/mstypulkowski/CIF/saves/Saved_models_2101_backup/'
load_models_dir: '/home/mstypulkowski/CIF/saves/Saved_models_2101/'
data_dir: '/home/mstypulkowski/CIF/data/ShapeNet/shapenet.npz'
losses: '/home/mstypulkowski/CIF/saves/losses2101.txt'

init_w: False # set True unless precomputed
use_EMD: False # False - Chamfer Distance
load_models: False # set False unless pretrained
use_new_f: True
use_new_g: True
use_random_dataloader: False

batch_size: 2
batch_size_if_random_split: 3000
n_epochs: 1000
n_neurons: 512
n_flows_F: 5
n_flows_G: 3
l_rate: 0.0001
emb_dim: 64
x_noise: 0.0001
w_noise: 0.02
prior_z_var: 1.0
prior_e_var: 1.0

# for test reconstruction - embeddings training
embs_dir: '/home/mstypulkowski/CIF/saves/embeddings/'
load_embs: False
l_rate4recon: 0.1
id4recon: 3

# post training tuning
train_F: True
train_G: True

####### PointFlow-related args #######

# these two does not influence the result, they're neede for comptability
# with point flow loaders
tr_sample_size: 1024
te_sample_size: 1024
#

root_dir: '/home/mstypulkowski/CIF/data/ShapeNetCore.v2.PC15k'
normalize_per_shape: false
normalize_std_per_axis: false
scale: 1.0
categories: ["chair"]