save_models_dir: '/home/mstypulkowski/CIF/saves/Saved_models/'
save_models_dir_backup: '/home/mstypulkowski/CIF/saves/Saved_models_backup/'
load_models_dir: '/home/mstypulkowski/CIF/saves/Saved_models/'
data_dir: '/home/mstypulkowski/CIF/data/ShapeNet/shapenet.npz'
losses: '/home/mstypulkowski/CIF/saves/losses.txt'

init_w: False
load_models: True

batch_size: 3000
n_epochs: 1000
n_neurons: 512
n_flows_F: 10
n_flows_G: 10
l_rate: 0.0001
emb_dim: 64

embs_dir: '/home/mstypulkowski/CIF/saves/embeddings/'
load_embs: False
l_rate4recon: 0.1
id4recon: 3