root_dir: TODO
root_embs_dir: TODO
load_models_dir: TODO
resume_dataset_mean: TODO
resume_dataset_std: TODO

use_random_dataloader: True

batch_size_if_random_split: 64
n_flows_F: 10
n_flows_G: 5
n_neurons: 512
type_emb: '2r'
arch_type: 'dense_net'
emb_dim: 32

use_EMD: False

# sampling
n_samples: 10
n_points: 2048
prior_z_var: 1.0
prior_e_var: !!python/list [0.75, 1.0, 1.25, 1.5]
#prior_e_var: 1.0

# interpolation
interpolation_ids: !!python/list [0, 1, 2, 3]
n_midsamples: 25

####### PointNet encoder style args #######
# total number of points in a single batch is equal to the number of objects
# per batch, a'ka batch_size, and number of points
num_of_points_per_object: 60
load_pretrained: true
pretrained_path: TODO

####### PointFlow-related args #######

# these two does not influence the result, they're neede for comptability
# with point flow loaders
tr_sample_size: 2048
te_sample_size: 2048
#
normalize_per_shape: false
normalize_std_per_axis: false
scale: 1.0
categories: ["airplane"]