root_dir: '/home/mstypulkowski/CIF/data/ShapeNetCore.v2.PC15k'
save_models_dir: '/home/mstypulkowski/CIF/saves/Saved_models_ext_h/'
save_models_dir_backup: '/home/mstypulkowski/CIF/saves/Saved_models_ext_h/'
load_models_dir: '/home/mstypulkowski/CIF/saves/Saved_models_ext_h/'
resume_dataset_mean: '/home/mstypulkowski/CIF/saves/Saved_models_ext_h/train_set_mean.npy'
resume_dataset_std: '/home/mstypulkowski/CIF/saves/Saved_models_ext_h/train_set_std.npy'
losses: '/home/mstypulkowski/CIF/saves/losses_ext_h.txt'
tensorboard_dir: '/home/mstypulkowski/CIF/tensorboard/'

init_w: False # set True unless precomputed
use_EMD: False # False - Chamfer Distance
load_models: False # set False unless pretrained
use_new_f: False
use_new_g: False
use_random_dataloader: True

batch_size: 2
batch_size_if_random_split: 4500
n_epochs: 1000
n_neurons: 512
type_emb: '2r'
n_flows_F: 10
n_flows_G: 5
l_rate: 0.0001
emb_dim: 64
x_noise: 0.0001
w_noise: 0.01
prior_z_var: 1.0
prior_e_var: 1.0

# for test reconstruction - embeddings training
# embs_dir: ''
load_embs: False
l_rate4recon: 0.1
id4recon: 3

# post training tuning
train_F: True
train_G: True

####### PointFlow-related args #######

# these two does not influence the result, they're needed for comptability
# with point flow loaders
tr_sample_size: 1024
te_sample_size: 1024
#

normalize_per_shape: false
normalize_std_per_axis: false
scale: 1.0
categories: ["chair"]