root_dir: '/home/mstypulkowski/CIF/data/ShapeNetCore.v2.PC15k'
root_embs_dir: '/home/mstypulkowski/CIF/data/ShapeNetCore.v2.PC15k_embs'
load_models_dir: '/home/mstypulkowski/CIF/saves/Saved_models_chair_point_net_encoder/'
embs_dir: '/home/mstypulkowski/CIF/saves/embeddings_chair_point_net_encoder/'
plots_dir: '/home/mstypulkowski/CIF/saves/plots_chair_point_net_encoder/'
resume_dataset_mean: '/home/mstypulkowski/CIF/saves/Saved_models_chair_point_net_encoder/train_set_mean.npy'
resume_dataset_std: '/home/mstypulkowski/CIF/saves/Saved_models_chair_point_net_encoder/train_set_std.npy'
metrics_dir: '/home/mstypulkowski/CIF/saves/metrics_chair_point_net_encoder.txt'

use_new_f: False
use_new_g: False
use_random_dataloader: True

batch_size_if_random_split: 64
n_flows_F: 10
n_flows_G: 5
n_neurons: 512
type_emb: '2r'
arch_type: 'dense_net'
emb_dim: 32

n_samples: 10
n_points: 2048
id4recon: 3

start_ids: !!python/tuple [0,1,3,5]
stop_ids: !!python/tuple [1,3,5,0]
n_midsamples: 10

use_EMD: False

prior_z_var: 1.0
#prior_e_var: !!python/list [1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5]
prior_e_var: 1.0

x_noise: 0.0001
w_noise: 0.01

####### PointNet encoder style args #######
# total number of points in a single batch is equal to the number of objects
# per batch, a'ka batch_size, and number of points
num_of_points_per_object: 60
load_pretrained: true
pretrained_path: "saves/pretrained_models/encoder/all.pt"

####### PointFlow-related args #######

# these two does not influence the result, they're neede for comptability
# with point flow loaders
tr_sample_size: 2048
te_sample_size: 2048
#
normalize_per_shape: false
normalize_std_per_axis: false
scale: 1.0
categories: ["chair"]

####### Visualization related args #######
renderer_port: 8000
are_shapes_rotated_by_default: false
renders_save_dir: "renders/pointnet_from_scratch/"
